version: "3"
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password

  redis:
    image: redis
    restart: on-failure    

  slacktunes:
    build: ./
    restart: on-failure
    ports:
      - "80:8000"
    volumes:
      - ./:/app
    depends_on:
      - db
      - redis
    command: ["python", "/app/application.py"]
