version: "3"
services:

  nginx:
    image: nginx
    container_name: nginx
    restart: always
    volumes:
      - ./nginx/prod/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443
    depends_on:
      - slacktunes