version: "3"
services:
  nginx:
    image: nginx
    restart: on-failure

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./database-init.sql:/docker-entrypoint-initdb.d/databases.sql

  redis:
    image: redis
    restart: on-failure    

  slacktunes:
    build: ./
    restart: on-failure
    volumes:
      - ./:/app
    depends_on:
      - db
      - redis
    command: ["python", "/app/application.py"]
