version: "3"
services:
  nginx:
    image: nginx
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8000:80
    depends_on:
      - slacktunes

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    tty: true
    volumes:
      - ./database-init.sql:/docker-entrypoint-initdb.d/databases.sql

  redis:
    image: redis
    restart: on-failure    

  slacktunes:
    build: ./
    restart: always
    container_name: slacktunes_backend
    volumes:
      - ./:/app
    env_file:
      - dev.env
    depends_on:
      - db
      - redis
    tty: true
    command: [ "uwsgi", "--ini", "uwsgi.ini" ]
