version: "3"
services:
  nginx:
    image: nginx
    restart: on-failure
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/error.log:/etc/nginx/error_log.log
      - /etc/letsencrypt/:/etc/letsencrypt/
    ports:
      - 80:80
      - 443:443
    depends_on:
      - slacktunes

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./database-init.sql:/docker-entrypoint-initdb.d/databases.sql

  redis:
    image: redis
    restart: on-failure    

  slacktunes:
    build: ./
    restart: on-failure
    container_name: slacktunes
    volumes:
      - ./:/app
    depends_on:
      - db
      - redis
    command: ["python", "/app/application.py"]
