"""empty message

Revision ID: 18fe3a0869fa
Revises: 2ce2ad72b210
Create Date: 2019-07-30 03:33:01.101215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18fe3a0869fa'
down_revision = '2ce2ad72b210'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_service_user', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_service_user')
    # ### end Alembic commands ###
