"""empty message

Revision ID: 6744f55ab672
Revises: 
Create Date: 2019-04-21 11:21:39.591841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6744f55ab672'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slack_id', sa.Integer(), nullable=True),
    sa.Column('slack_access_token', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('slack_id', sa.String(length=100), nullable=True),
    sa.Column('last_posted_auth_error', sa.DateTime(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_slack_id'), 'user', ['slack_id'], unique=True)
    op.create_table('credential',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('service', sa.Enum('YOUTUBE', 'SPOTIFY', 'GMUSIC', name='musicservice'), nullable=True),
    sa.Column('credentials', sa.String(length=5000), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'service', name='_user_service_constraint')
    )
    op.create_index(op.f('ix_credential_user_id'), 'credential', ['user_id'], unique=False)
    op.create_table('playlist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('channel_id', sa.String(length=100), nullable=True),
    sa.Column('service', sa.Enum('YOUTUBE', 'SPOTIFY', 'GMUSIC', name='musicservice'), nullable=True),
    sa.Column('service_id', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('service', 'service_id', name='_service_serviceid_constraint')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('playlist')
    op.drop_index(op.f('ix_credential_user_id'), table_name='credential')
    op.drop_table('credential')
    op.drop_index(op.f('ix_user_slack_id'), table_name='user')
    op.drop_table('user')
    op.drop_table('team')
    # ### end Alembic commands ###
